import type { CycleDecision } from "./cycle-decision.engine";
import { estimate1RM } from "../utils/estimated-1rm.util";

/**
 * Deterministic per-exercise progression engine.
 *
 * See docs/TRAINING_PROGRESSION_ARCHITECTURE.md for the full design record
 * (§3 API, §4 policy selection, §2 precedence rule). Independently designed
 * from this repo's own conventions (cycle-decision.engine.ts's
 * DecisionEngineResult/reasonCodes shape) — no openGym source was read
 * (AGPL-3.0, behavior-only reference per docs/OPENGYM_VS_FITNESS_ASSISTANT_GAP_ANALYSIS.md).
 *
 * Pure function: no I/O, no Prisma, no LLM calls — every branch is
 * unit-testable with plain data (see exercise-progression.engine.test.ts).
 *
 * PRECEDENCE RULE (docs/TRAINING_PROGRESSION_ARCHITECTURE.md §2): the
 * training-cycle engine's current decision bounds what this engine may
 * propose. This engine never overrides the cycle engine — it only computes
 * a local, per-exercise signal and then applies the cycle's envelope.
 */

export type LoggingMode =
  | "REPS_LOAD"
  | "BODYWEIGHT_REPS"
  | "TIME"
  | "TIME_LOAD"
  | "DISTANCE_TIME";

export type ProgressionPolicy =
  | "LINEAR"
  | "DOUBLE_PROGRESSION"
  | "AUTOREGULATED_RIR"
  | "AMRAP_READINESS"
  | "BODYWEIGHT_REP_CLIMB"
  | "TIMED_PROGRESSION";

export type ExperienceLevel = "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "UNKNOWN";

export type ExerciseProgressionStatus =
  | "KEEP"
  | "INCREASE_LOAD"
  | "INCREASE_REPS"
  | "INCREASE_SETS"
  | "DELOAD"
  | "REVIEW"
  | "INSUFFICIENT_DATA";

/** One logged set, already resolved to plain numbers by the caller. The
 * caller (workout.service.ts / a future controller) is responsible for
 * fetching real WorkoutSet rows — this file never touches Prisma. */
export interface PerformanceSetRow {
  weightKg: number | null;
  reps: number | null;
  rir: number | null;
  rpe: number | null;
  durationSeconds: number | null;
  distanceMeters: number | null;
  completed: boolean;
  /** SET_TYPES from fitness.models.ts — "WARMUP" sets are excluded by this
   * engine defensively (industry convention, see gap analysis + research
   * sources doc), even if the caller forgot to pre-filter them. */
  setType: string | null;
  /** Immutable snapshot copied from the planned set when the workout starts.
   * Optional keeps old callers/history fully backward compatible. */
  isAmrap?: boolean;
  amrapMinReps?: number | null;
}

export interface ExercisePerformanceSession {
  date: Date;
  sets: PerformanceSetRow[];
}

export interface ExerciseProgressionInput {
  loggingMode: LoggingMode;
  experienceLevel: ExperienceLevel;
  /** Most-recent-first. Only completed, non-warmup sets are used; callers
   * may pass raw history, this engine filters defensively. */
  recentSessions: ExercisePerformanceSession[];
  /** Current training-cycle decision, if any active cycle exists for this
   * user. `null` when there is no active cycle — treated the same as
   * "KEEP" (no envelope restriction), matching how workout logging today
   * already works independently of any cycle. */
  cycleDecision: CycleDecision | null;
}

export interface ExerciseProgressionResult {
  status: ExerciseProgressionStatus;
  policyUsed: ProgressionPolicy | null;
  currentPerformance: {
    weightKg: number | null;
    reps: number | null;
    durationSeconds: number | null;
    distanceMeters: number | null;
    setCount: number;
  } | null;
  nextTarget: {
    weightKg: number | null;
    reps: number | null;
    durationSeconds: number | null;
  } | null;
  loadChangeKg: number | null;
  repChange: number | null;
  /** Machine-readable reason codes — natural language is generated by the
   * UI/AI layer from these, never returned as source of truth here (matches
   * DecisionEngineResult's existing convention in cycle-decision.engine.ts). */
  reasonCodes: string[];
  cycleContext: CycleDecision | "NONE";
  dataQuality: "SUFFICIENT" | "LOW_SAMPLE" | "NONE";
  amrapPerformance: {
    achievedReps: number;
    minimumReps: number;
    marginReps: number;
  } | null;
}

// ---- Product-heuristic thresholds (NOT scientific claims — see
// docs/OPENGYM_RESEARCH_SOURCES.md's "product heuristic" table). Direction
// (progress when performance allows, back off on repeated failure) is
// evidence-supported per docs/gym-fitness-research.md §2; exact numbers
// below are product defaults, overridable the same way cycle-thresholds.config.ts
// already makes cycle-level thresholds overridable, if this ever needs to
// become configurable too. ----
const LINEAR_LOAD_STEP_FRACTION = 0.05; // +5% of current load per successful session
const BODYWEIGHT_REP_STEP = 2; // +2 reps target once current top of range is met
const CONSECUTIVE_MISSES_BEFORE_DELOAD = 2;
const DELOAD_LOAD_REDUCTION_FRACTION = 0.1; // -10%, matches training-cycle-classification.service.ts's own deload-scale convention
const LOW_RIR_MISS_THRESHOLD = 0; // RIR <= 0 on a set counts as "no room left" for that set
const HIGH_RIR_HEADROOM_THRESHOLD = 2; // avg RIR >= 2 means there was room to add load
const AMRAP_LOAD_READY_MARGIN_REPS = 2;
const AMRAP_BODYWEIGHT_MINIMUM_STEP = 1;

function isUsableSet(s: PerformanceSetRow): boolean {
  return s.completed && s.setType !== "WARMUP";
}

function selectProgressionPolicy(
  loggingMode: LoggingMode,
  experienceLevel: ExperienceLevel,
  hasRirData: boolean,
): ProgressionPolicy {
  if (loggingMode === "BODYWEIGHT_REPS") return "BODYWEIGHT_REP_CLIMB";
  if (loggingMode === "TIME" || loggingMode === "TIME_LOAD" || loggingMode === "DISTANCE_TIME") {
    return "TIMED_PROGRESSION";
  }
  // REPS_LOAD
  if (experienceLevel === "ADVANCED" && hasRirData) return "AUTOREGULATED_RIR";
  if (experienceLevel === "INTERMEDIATE" || experienceLevel === "ADVANCED") return "DOUBLE_PROGRESSION";
  // BEGINNER / UNKNOWN — UNKNOWN treated like BEGINNER, matching
  // cycle-decision.engine.ts's own stated convention for this field.
  return "LINEAR";
}

interface SessionSummary {
  maxWeightKg: number | null;
  totalReps: number | null;
  avgRir: number | null;
  maxDurationSeconds: number | null;
  maxDistanceMeters: number | null;
  setCount: number;
  anySetMissedRir: boolean;
  amrapAchievedReps: number | null;
  amrapMinReps: number | null;
  amrapMinMarginReps: number | null;
}

function summarizeSession(session: ExercisePerformanceSession): SessionSummary | null {
  const sets = session.sets.filter(isUsableSet);
  if (sets.length === 0) return null;

  let maxWeightKg: number | null = null;
  let totalReps: number | null = null;
  let maxDurationSeconds: number | null = null;
  let maxDistanceMeters: number | null = null;
  const rirValues: number[] = [];
  let anySetMissedRir = false;
  let amrapAchievedReps: number | null = null;
  let amrapMinReps: number | null = null;
  let amrapMinMarginReps: number | null = null;

  for (const s of sets) {
    if (s.weightKg != null) maxWeightKg = Math.max(maxWeightKg ?? -Infinity, s.weightKg);
    if (s.reps != null) totalReps = (totalReps ?? 0) + s.reps;
    if (s.durationSeconds != null) {
      maxDurationSeconds = Math.max(maxDurationSeconds ?? -Infinity, s.durationSeconds);
    }
    if (s.distanceMeters != null) {
      maxDistanceMeters = Math.max(maxDistanceMeters ?? -Infinity, s.distanceMeters);
    }
    if (s.rir != null) {
      rirValues.push(s.rir);
      // RIR 0 is expected on a genuine AMRAP and must not masquerade as a
      // failed straight-set prescription.
      if (!s.isAmrap && s.rir <= LOW_RIR_MISS_THRESHOLD) anySetMissedRir = true;
    }
    if (s.isAmrap && s.reps != null && s.amrapMinReps != null) {
      const margin = s.reps - s.amrapMinReps;
      amrapAchievedReps = Math.max(amrapAchievedReps ?? -Infinity, s.reps);
      amrapMinReps = Math.max(amrapMinReps ?? -Infinity, s.amrapMinReps);
      // Multiple AMRAP probes in one session must all clear the prescription
      // before an automatic increase is allowed.
      amrapMinMarginReps = Math.min(amrapMinMarginReps ?? Infinity, margin);
    }
  }

  return {
    maxWeightKg,
    totalReps,
    avgRir: rirValues.length > 0 ? rirValues.reduce((a, b) => a + b, 0) / rirValues.length : null,
    maxDurationSeconds,
    maxDistanceMeters,
    setCount: sets.length,
    anySetMissedRir,
    amrapAchievedReps,
    amrapMinReps,
    amrapMinMarginReps,
  };
}

function sessionRegressed(current: SessionSummary, previous: SessionSummary): boolean {
  if (current.amrapMinMarginReps != null) return current.amrapMinMarginReps < 0;
  return (
    (current.maxWeightKg ?? 0) < (previous.maxWeightKg ?? 0) ||
    ((current.maxWeightKg ?? 0) === (previous.maxWeightKg ?? 0) &&
      (current.totalReps ?? 0) < (previous.totalReps ?? 0)) ||
    current.anySetMissedRir
  );
}

function roundToStep(value: number, step = 0.5): number {
  return Math.round(value / step) * step;
}

export function evaluateExerciseProgression(
  input: ExerciseProgressionInput,
): ExerciseProgressionResult {
  const summaries = input.recentSessions
    .map(summarizeSession)
    .filter((s): s is SessionSummary => s !== null);

  const dataQuality: ExerciseProgressionResult["dataQuality"] =
    summaries.length === 0 ? "NONE" : summaries.length === 1 ? "LOW_SAMPLE" : "SUFFICIENT";

  const cycleContext: CycleDecision | "NONE" = input.cycleDecision ?? "NONE";

  if (dataQuality === "NONE") {
    return {
      status: "INSUFFICIENT_DATA",
      policyUsed: null,
      currentPerformance: null,
      nextTarget: null,
      loadChangeKg: null,
      repChange: null,
      reasonCodes: ["NO_VALID_SET_HISTORY"],
      cycleContext,
      dataQuality,
      amrapPerformance: null,
    };
  }

  const latest = summaries[0];
  const hasRirData = summaries.some((s) => s.avgRir != null);
  const hasQualifiedAmrap =
    latest.amrapMinMarginReps != null &&
    (input.loggingMode === "REPS_LOAD" || input.loggingMode === "BODYWEIGHT_REPS");
  const policyUsed: ProgressionPolicy = hasQualifiedAmrap
    ? "AMRAP_READINESS"
    : selectProgressionPolicy(input.loggingMode, input.experienceLevel, hasRirData);
  const amrapPerformance =
    hasQualifiedAmrap && latest.amrapAchievedReps != null && latest.amrapMinReps != null
      ? {
          achievedReps: latest.amrapAchievedReps,
          minimumReps: latest.amrapMinReps,
          marginReps: latest.amrapMinMarginReps ?? 0,
        }
      : null;

  const currentPerformance = {
    weightKg: latest.maxWeightKg,
    reps: latest.totalReps,
    durationSeconds: latest.maxDurationSeconds,
    distanceMeters: latest.maxDistanceMeters,
    setCount: latest.setCount,
  };

  if (dataQuality === "LOW_SAMPLE") {
    return {
      status: "INSUFFICIENT_DATA",
      policyUsed,
      currentPerformance,
      nextTarget: null,
      loadChangeKg: null,
      repChange: null,
      reasonCodes: ["ONLY_ONE_SESSION_LOGGED_NEED_AT_LEAST_TWO_TO_COMPARE"],
      cycleContext,
      dataQuality,
      amrapPerformance,
    };
  }

  const previous = summaries[1];
  const reasonCodes: string[] = [];

  const improved =
    (latest.maxWeightKg ?? 0) > (previous.maxWeightKg ?? 0) ||
    ((latest.maxWeightKg ?? 0) === (previous.maxWeightKg ?? 0) &&
      (latest.totalReps ?? 0) > (previous.totalReps ?? 0)) ||
    (latest.maxDurationSeconds ?? 0) > (previous.maxDurationSeconds ?? 0) ||
    (latest.maxDistanceMeters ?? 0) > (previous.maxDistanceMeters ?? 0);

  const regressed = sessionRegressed(latest, previous);

  // Count consecutive regressions walking back through history for the
  // deload trigger (needs >= CONSECUTIVE_MISSES_BEFORE_DELOAD sessions of
  // regression in a row, not just the latest one).
  let consecutiveMisses = 0;
  for (let i = 0; i < summaries.length - 1; i++) {
    const cur = summaries[i];
    const prev = summaries[i + 1];
    const curRegressed = sessionRegressed(cur, prev);
    if (curRegressed) consecutiveMisses++;
    else break;
  }

  let status: ExerciseProgressionStatus;
  let loadChangeKg: number | null = null;
  let repChange: number | null = null;
  let nextTarget: ExerciseProgressionResult["nextTarget"] = null;

  if (consecutiveMisses >= CONSECUTIVE_MISSES_BEFORE_DELOAD) {
    status = "DELOAD";
    reasonCodes.push("MISSED_TARGET_TWO_OR_MORE_SESSIONS_IN_A_ROW");
    if (latest.maxWeightKg != null) {
      loadChangeKg = -roundToStep(latest.maxWeightKg * DELOAD_LOAD_REDUCTION_FRACTION);
      nextTarget = { weightKg: roundToStep(latest.maxWeightKg + loadChangeKg), reps: null, durationSeconds: null };
    }
  } else if (policyUsed === "AMRAP_READINESS") {
    const margin = latest.amrapMinMarginReps ?? -Infinity;
    if (margin >= AMRAP_LOAD_READY_MARGIN_REPS) {
      if (input.loggingMode === "BODYWEIGHT_REPS") {
        status = "INCREASE_REPS";
        repChange = AMRAP_BODYWEIGHT_MINIMUM_STEP;
        nextTarget = {
          weightKg: null,
          reps: (latest.amrapMinReps ?? 0) + AMRAP_BODYWEIGHT_MINIMUM_STEP,
          durationSeconds: null,
        };
        reasonCodes.push("AMRAP_EXCEEDED_MIN_REPS_RAISE_MINIMUM");
      } else {
        status = "INCREASE_LOAD";
        const base = latest.maxWeightKg ?? 0;
        loadChangeKg = roundToStep(base * LINEAR_LOAD_STEP_FRACTION);
        nextTarget = {
          weightKg: roundToStep(base + loadChangeKg),
          reps: latest.amrapMinReps,
          durationSeconds: null,
        };
        reasonCodes.push("AMRAP_EXCEEDED_MIN_REPS_LOAD_READY");
      }
    } else if (margin >= 0) {
      status = "KEEP";
      reasonCodes.push("AMRAP_MIN_REPS_MET_HOLD_CURRENT_TARGET");
    } else {
      status = "KEEP";
      reasonCodes.push("AMRAP_MIN_REPS_MISSED_ONCE_REPEAT_BEFORE_DELOAD");
    }
  } else if (policyUsed === "BODYWEIGHT_REP_CLIMB") {
    if (improved || (latest.avgRir ?? 0) >= HIGH_RIR_HEADROOM_THRESHOLD) {
      status = "INCREASE_REPS";
      repChange = BODYWEIGHT_REP_STEP;
      reasonCodes.push("BODYWEIGHT_REPS_IMPROVED_OR_HAD_HEADROOM");
      nextTarget = { weightKg: null, reps: (latest.totalReps ?? 0) + BODYWEIGHT_REP_STEP, durationSeconds: null };
    } else {
      status = "KEEP";
      reasonCodes.push("BODYWEIGHT_REPS_STABLE_NOT_YET_READY_TO_ADD_REPS");
    }
  } else if (policyUsed === "TIMED_PROGRESSION") {
    if (improved) {
      status = "INCREASE_LOAD"; // "load" here means duration/distance target, per architecture doc §4
      reasonCodes.push("TIMED_EXERCISE_DURATION_OR_DISTANCE_IMPROVED");
      nextTarget = {
        weightKg: null,
        reps: null,
        durationSeconds: latest.maxDurationSeconds != null ? latest.maxDurationSeconds + 5 : null,
      };
    } else {
      status = "KEEP";
      reasonCodes.push("TIMED_EXERCISE_NO_IMPROVEMENT_YET");
    }
  } else if (policyUsed === "DOUBLE_PROGRESSION" || policyUsed === "AUTOREGULATED_RIR") {
    if (improved && !latest.anySetMissedRir) {
      status = "INCREASE_LOAD";
      const base = latest.maxWeightKg ?? 0;
      loadChangeKg = roundToStep(base * LINEAR_LOAD_STEP_FRACTION);
      nextTarget = { weightKg: roundToStep(base + loadChangeKg), reps: null, durationSeconds: null };
      reasonCodes.push(
        policyUsed === "AUTOREGULATED_RIR"
          ? "RIR_TARGET_MET_WITH_HEADROOM_TO_SPARE"
          : "TOP_OF_REP_RANGE_REACHED_ON_ALL_SETS",
      );
    } else if (regressed) {
      status = "REVIEW";
      reasonCodes.push("PERFORMANCE_DIPPED_SINGLE_SESSION_REVIEW_BEFORE_CHANGING_LOAD");
    } else {
      status = "INCREASE_REPS";
      repChange = 1;
      reasonCodes.push("BELOW_TOP_OF_REP_RANGE_ADD_A_REP_BEFORE_ADDING_LOAD");
    }
  } else {
    // LINEAR
    if (improved && !latest.anySetMissedRir) {
      status = "INCREASE_LOAD";
      const base = latest.maxWeightKg ?? 0;
      loadChangeKg = roundToStep(base * LINEAR_LOAD_STEP_FRACTION);
      nextTarget = { weightKg: roundToStep(base + loadChangeKg), reps: null, durationSeconds: null };
      reasonCodes.push("COMPLETED_ALL_PRESCRIBED_REPS_WITHIN_TARGET_RIR");
    } else {
      status = "KEEP";
      reasonCodes.push("REPEAT_SAME_LOAD_UNTIL_PRESCRIBED_REPS_MET_CLEANLY");
    }
  }

  // ---- Cycle-decision envelope (docs/TRAINING_PROGRESSION_ARCHITECTURE.md §2) ----
  if (input.cycleDecision === "DELOAD" && status !== "DELOAD") {
    status = "DELOAD";
    loadChangeKg = latest.maxWeightKg != null ? -roundToStep(latest.maxWeightKg * DELOAD_LOAD_REDUCTION_FRACTION) : null;
    repChange = null;
    nextTarget =
      latest.maxWeightKg != null && loadChangeKg != null
        ? { weightKg: roundToStep(latest.maxWeightKg + loadChangeKg), reps: null, durationSeconds: null }
        : null;
    reasonCodes.push("CYCLE_DELOAD_OVERRIDES_LOCAL_SIGNAL");
  } else if (input.cycleDecision === "REBUILD" && (status === "INCREASE_LOAD" || status === "INCREASE_REPS")) {
    status = "REVIEW";
    loadChangeKg = null;
    repChange = null;
    nextTarget = null;
    reasonCodes.push("CYCLE_REBUILD_BLOCKS_AUTOMATIC_LOCAL_INCREASE");
  }

  return {
    status,
    policyUsed,
    currentPerformance,
    nextTarget,
    loadChangeKg,
    repChange,
    reasonCodes,
    cycleContext,
    dataQuality,
    amrapPerformance,
  };
}

/** Exported for reuse by the PR engine / future callers that want the same
 * "what e1RM is this set worth" computation without duplicating the import. */
export function estimateSetE1rm(weightKg: number, reps: number): number {
  return estimate1RM(weightKg, reps);
}
