import { Response } from "express";
import path from "path";
import fs from "fs";
import { AuthRequest } from "../middleware/auth.middleware";
import { ptApplicationService } from "../services/pt_application.service";
import { verifyDocumentUrl, signPtApplicationDocumentUrls } from "../utils/ptDocumentUrl.util";
import { logger } from "@gym-coach/shared";

// Only plain filenames (as generated by multer: fieldname-timestamp-random.ext)
// are ever accepted — rejects path traversal (`..`, `/`) outright.
const SAFE_FILENAME_RE = /^[a-zA-Z0-9_.-]+$/;
const UPLOADS_DIR = path.join(process.cwd(), "uploads", "pt-applications");

export const ptApplicationController = {
  async getMe(req: AuthRequest, res: Response) {
    try {
      const app = await ptApplicationService.getMe(req.user!.id);
      return res.json(app);
    } catch (error: any) {
      logger.error(error, "Get my PT application error");
      return res.status(500).json({ error: "Internal server error" });
    }
  },

  async saveDraft(req: AuthRequest, res: Response) {
    try {
      const app = await ptApplicationService.saveDraft(req.user!.id, req.body);
      return res.json(app);
    } catch (error: any) {
      logger.error(error, "Save PT application draft error");
      return res.status(400).json({ error: error.message });
    }
  },

  async submit(req: AuthRequest, res: Response) {
    try {
      const app = await ptApplicationService.submit(req.user!.id);
      return res.json(app);
    } catch (error: any) {
      logger.error(error, "Submit PT application error");
      return res.status(400).json({ error: error.message });
    }
  },

  async upload(req: AuthRequest, res: Response) {
    try {
      if (!req.file) {
        return res.status(400).json({ error: "No file uploaded" });
      }
      // `url` is the STABLE, canonical reference the frontend stores in form
      // state and round-trips through saveDraft — it is deliberately never
      // itself a signed/expiring link (see pt_application.repository.ts's
      // upsertDraft, which canonicalizes any signed link the client might
      // echo back anyway, so this is defense in depth, not the only guard).
      // `previewUrl` is a short-lived signed link the browser can actually
      // load via a plain <img src> right after upload (no static file
      // serving of this directory exists anymore — see app.ts).
      const url = `/uploads/pt-applications/${req.file.filename}`;
      return res.json({
        url,
        previewUrl: signPtApplicationDocumentUrls({ portraitPhotoUrl: url })
          .portraitPhotoUrl,
        filename: req.file.originalname,
      });
    } catch (error: any) {
      logger.error(error, "PT application upload error");
      return res.status(500).json({ error: "Internal server error" });
    }
  },

  /**
   * Serves a PT application document. Requires no Authorization header (a
   * plain <img src=...> works) — authorization is proven by the request's
   * `exp`/`sig` query params, which are only ever handed out by getMe/
   * getById/listApplications/adminReviewAction (all of which already run
   * behind authMiddleware + the existing own-application/ADMIN-only route
   * gates). See ptDocumentUrl.util.ts's doc comment for the full rationale.
   */
  async getDocument(req: AuthRequest, res: Response) {
    const { filename } = req.params;
    const { exp, sig } = req.query;

    if (!SAFE_FILENAME_RE.test(filename)) {
      return res.status(400).json({ error: "Invalid filename" });
    }
    if (!verifyDocumentUrl(filename, exp as string | undefined, sig as string | undefined)) {
      return res.status(403).json({ error: "Invalid or expired link" });
    }

    const filePath = path.join(UPLOADS_DIR, filename);
    // Defense in depth against path.join surprises: the resolved path must
    // still live inside UPLOADS_DIR.
    if (!filePath.startsWith(UPLOADS_DIR + path.sep) && filePath !== UPLOADS_DIR) {
      return res.status(400).json({ error: "Invalid filename" });
    }
    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: "Not found" });
    }
    return res.sendFile(filePath);
  },

  // Admin endpoints
  async listApplications(req: AuthRequest, res: Response) {
    try {
      const apps = await ptApplicationService.listApplications(req.query);
      const mapped = apps.map((app: any) => ({
        ...app,
        user: {
          firstName: app.userProfile?.firstName,
          lastName: app.userProfile?.lastName,
          email: app.userProfile?.email || "N/A", // Fallback if email not in profile
        },
      }));
      return res.json(mapped);
    } catch (error: any) {
      logger.error(error, "List PT applications error");
      return res.status(500).json({ error: "Internal server error" });
    }
  },

  async getById(req: AuthRequest, res: Response) {
    try {
      const app: any = await ptApplicationService.getById(req.params.id);
      if (!app) return res.status(404).json({ error: "Application not found" });

      const mapped = {
        ...app,
        user: {
          firstName: app.userProfile?.firstName,
          lastName: app.userProfile?.lastName,
          email: app.userProfile?.email || "N/A",
        },
      };
      return res.json(mapped);
    } catch (error: any) {
      logger.error(error, "Get PT application by ID error");
      return res.status(500).json({ error: "Internal server error" });
    }
  },

  async reviewAction(req: AuthRequest, res: Response) {
    try {
      const { action } = req.params;
      const app = await ptApplicationService.adminReviewAction(
        req.params.id,
        action as any,
        req.body,
        req.user!.id,
      );
      return res.json(app);
    } catch (error: any) {
      logger.error(error, "Admin review action error");
      return res.status(400).json({ error: error.message });
    }
  },
};
